---
title: "PATTERNS OF SEDENTARY TIME ACCUMULATION IN NON-INSTITUTIONALIZED US POPULATION: A 2003-2006 NHANES AGE-BASED ANALYSIS"
author: "Pierre-Yves de Müllenheim"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    df_print: paged
    code_folding: show
toc-title: "Summary"
---

```{css, echo=FALSE}
.title {
  font-weight: bold;
}

h1 {
  font-size: 23px;
  font-weight: bold;
}
h2 {
  font-size: 23px;
  font-weight: bold;
}
h3 {
  font-size: 21px;
}
p.caption {
  color: #777;
  margin-top: 10px;
}
p code {
  white-space: inherit;
}
pre {
  word-break: normal;
  word-wrap: normal;
}
pre code {
  white-space: inherit;
}
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
options(knitr.table.number = Inf)
ggplot2::theme_set(ggplot2::theme_bw())
palette <- "Greens"
```

# Load packages & functions
```{r}
library(dplyr)
library(forcats)
library(ggplot2)
library(RColorBrewer)
library(rnhanesdata)
library(scales)
library(skimr)
library(survey)
library(readr)
library(targets)
library(tidyr)
source("R/get_adj_quantiles_by.R")
```

# Remind accelerometer processing settings
```{r}
read_csv2("config.csv")
```

# Load data 
```{r}
tar_load(df_final)
```

# Inspect completion rate
```{r, out.width='100%', fig.height=5, fig.cap="No data is available for preschoolers"}
df_final |> 
  group_by(CAT_AGE) |> 
  mutate(
    minutes_SED = if_else(valid_days >= 4, minutes_SED, NA),
    mean_breaks = if_else(valid_days >= 4, mean_breaks, NA),
    alpha = if_else(valid_days >= 4, alpha, NA),
    MBD = if_else(valid_days >= 4, MBD, NA),
    UBD = if_else(valid_days >= 4, UBD, NA),
    gini = if_else(valid_days >= 4, gini, NA)
    ) |> 
  select(CAT_AGE, minutes_SED, mean_breaks:gini) |> 
  skim() |> 
  select(skim_variable, CAT_AGE, complete_rate) |> 
  mutate(skim_variable = as.factor(skim_variable) |> 
           fct_relevel("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini") |>
           fct_recode(
             "Sedentary minutes" = "minutes_SED",
             "Mean sedentary breaks" = "mean_breaks",
             "Median bout duration (min)" = "MBD",
             "Usual bout duration (min)" = "UBD",
             "Alpha" = "alpha", 
             "Gini" = "gini"
             )
         ) |> 
  ggplot(aes(x = CAT_AGE, y = complete_rate * 100, fill = CAT_AGE)) +
  geom_bar(stat = "identity") +
  labs(x = "", y = "Completion rate") +
  scale_y_continuous(labels = label_percent(scale = 1), limits = c(0, 100)) +
  scale_fill_brewer(palette = palette) +
  facet_wrap(~ skim_variable, nrow = 2) +
  theme(
    axis.title.y = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )
```

# Reweight sample participants
```{r}
df_final_rw <-
  reweight_accel(
    df_final,
    age_bks = c(0, 6, 13, 18, 65, Inf),
    right = FALSE
  )
```

# Define survey design
## Set general design
```{r}
design <-
  svydesign(
    ids = ~ SDMVPSU,
    strata = ~ SDMVSTRA,
    weights = ~ wtmec4yr_adj,
    data = df_final_rw,
    nest = TRUE
  )
```

# Subset general design to target people with a at least 4 valid days
```{r}
design_valid_pam <- 
  subset(
    x = design, 
    subset = valid_days >= 4
  )
```

# Get quantiles for sedentary time accumulation metrics by age

## Get estimates
```{r}
metric_quantiles <-
  lapply(
    c("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini"),
    get_adj_quantiles_by,
    by = "CAT_AGE",
    design = design_valid_pam
    ) |> 
  bind_rows() |> 
  mutate(metric = as.factor(metric) |> 
           fct_relevel("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini") |>
           fct_recode(
             "Sedentary minutes" = "minutes_SED",
             "Mean sedentary breaks" = "mean_breaks",
             "Median bout duration (min)" = "MBD",
             "Usual bout duration (min)" = "UBD",
             "Alpha" = "alpha", 
             "Gini" = "gini"
             )
  )


metric_quantiles |> 
  rename(
    Metric = metric,
    "Age category" = CAT_AGE
  )
```

## Visualize distributions
```{r, out.width = '100%', fig.cap="Boxplots have been manually constructed from the estimates of quantiles previously computed. Whiskers show the minimum and maximum. No data is available for preschoolers"}
fig <-
  ggplot(data = df_final_rw |>
         pivot_longer(
           c(minutes_SED, mean_breaks:gini),
           names_to = "metric",
           values_to = "val"
         ) |> 
  mutate(metric = as.factor(metric) |> 
           fct_relevel("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini") |>
           fct_recode(
             "Sedentary minutes" = "minutes_SED",
             "Mean sedentary breaks" = "mean_breaks",
             "Median bout duration (min)" = "MBD",
             "Usual bout duration (min)" = "UBD",
             "Alpha" = "alpha", 
             "Gini" = "gini"
             )
  )
       ) +
  geom_point(
    aes(x = CAT_AGE, y = val),
    position = position_jitter(seed = 123),
    alpha = 0.3
  ) +
  geom_boxplot(
    data = metric_quantiles,
    aes(
      x = CAT_AGE, 
      fill = CAT_AGE,
      ymin = q0,
      lower = q25, 
      middle = q50, 
      upper = q75, 
      ymax = q100
      ),
  stat = "identity"
  ) +
  labs(x = "", y = "") +
  scale_fill_brewer(palette = palette) +
  facet_wrap(~ metric, scales = "free_y") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )
fig
```


