---
title: "Patterns of sedentary time accumulation according to age in the United States: A 2003-2006 NHANES analysis"
author: "Pierre-Yves de Müllenheim"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
    number_sections: yes
    df_print: paged
    code_folding: show
toc-title: "Summary"
---

```{css, echo=FALSE}
.title {
  font-weight: bold;
}

h1 {
  font-size: 23px;
  font-weight: bold;
}
h2 {
  font-size: 23px;
  font-weight: bold;
}
h3 {
  font-size: 21px;
}
p.caption {
  color: #777;
  margin-top: 10px;
}
p code {
  white-space: inherit;
}
pre {
  word-break: normal;
  word-wrap: normal;
}
pre code {
  white-space: inherit;
}
.hljs-keyword {
    color: black;
    font-weight: bold;
}
```

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
options(knitr.table.number = Inf)
ggplot2::theme_set(ggplot2::theme_bw())
palette <- "Greens"
```

# Load packages & functions
```{r}
library(dplyr)
library(forcats)
library(ggplot2)
library(RColorBrewer)
library(readr)
library(rnhanesdata)
library(scales)
library(skimr)
library(stringr)
library(survey)
library(targets)
library(tidyr)
```

# Load data 
```{r}
withr::with_dir(rprojroot::find_root('_targets.R'),tar_load(df_final))
```

# Inspect completion rate
```{r, out.width='100%', fig.height=5}
df_final |> 
  group_by(CAT_AGE) |> 
  mutate(
    minutes_SED = if_else(valid_days >= 4, minutes_SED, NA),
    mean_breaks = if_else(valid_days >= 4, mean_breaks, NA),
    alpha = if_else(valid_days >= 4, alpha, NA),
    MBD = if_else(valid_days >= 4, MBD, NA),
    UBD = if_else(valid_days >= 4, UBD, NA),
    gini = if_else(valid_days >= 4, gini, NA)
    ) |> 
  select(CAT_AGE, minutes_SED, mean_breaks:gini) |> 
  skim() |> 
  select(skim_variable, CAT_AGE, complete_rate) |> 
  mutate(skim_variable = as.factor(skim_variable) |> 
           fct_relevel("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini") |>
           fct_recode(
             "Mean daily sedentary minutes" = "minutes_SED",
             "Mean daily sedentary breaks" = "mean_breaks",
             "Median bout duration (min)" = "MBD",
             "Usual bout duration (min)" = "UBD",
             "Power-law exponent alpha" = "alpha", 
             "Gini index" = "gini"
             )
         ) |> 
  filter(CAT_AGE != "Preschoolers") |> # There is no data for preschoolers
  ggplot(aes(x = CAT_AGE, y = complete_rate * 100, fill = CAT_AGE)) +
  geom_bar(stat = "identity") +
  labs(x = "", y = "Completion rate") +
  scale_y_continuous(labels = label_percent(scale = 1), limits = c(0, 100)) +
  scale_fill_brewer(palette = palette) +
  facet_wrap(~ skim_variable, nrow = 2) +
  theme(
    axis.title.y = element_text(size = 10),
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  )
```

# Get adjusted participant sampling weights for the 2003-2006 period
```{r}
df_final_rw <-
  reweight_accel(
    df_final,
    age_bks = c(0, 6, 13, 18, 65, Inf),
    right = FALSE
  )
```

# Define survey design
## Set general design
```{r}
design <-
  svydesign(
    ids = ~ SDMVPSU,
    strata = ~ SDMVSTRA,
    weights = ~ wtmec4yr_adj,
    data = df_final_rw,
    nest = TRUE
  )
```

# Subset general design to target people with at least 4 valid days
```{r}
design_valid_pam <- 
  subset(
    x = design, 
    subset = valid_days >= 4
  )
```

# Get quantiles for sedentary time accumulation metrics by age

## Get estimates
```{r}
metric_quantiles <-
  lapply(
    c("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini"),
    get_adj_quantiles_by,
    by = "CAT_AGE",
    design = design_valid_pam
    ) |> 
  bind_rows() |> 
  mutate(metric = as.factor(metric) |> 
           fct_relevel("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini") |>
           fct_recode(
             "Mean daily sedentary minutes" = "minutes_SED",
             "Mean daily sedentary breaks" = "mean_breaks",
             "Median bout duration (min)" = "MBD",
             "Usual bout duration (min)" = "UBD",
             "Power-law exponent alpha" = "alpha", 
             "Gini index" = "gini"
             )
  )

```

## Show estimates
```{r}
metric_quantiles |> 
  rename(
    Metric = metric,
    "Age category" = CAT_AGE
  )
```


## Visualize distributions
```{r, out.width = '100%', fig.height=6}
fig <-
  ggplot(data = df_final_rw |>  
         filter(CAT_AGE != "Preschoolers") |> # There is no data for preschoolers
         pivot_longer(
           c(minutes_SED, mean_breaks:gini),
           names_to = "metric",
           values_to = "val"
         ) |> 
  mutate(metric = as.factor(metric) |> 
           fct_relevel("minutes_SED", "mean_breaks", "alpha", "MBD", "UBD", "gini") |>
           fct_recode(
             "Mean daily sedentary minutes" = "minutes_SED",
             "Mean daily sedentary breaks" = "mean_breaks",
             "Median bout duration (min)" = "MBD",
             "Usual bout duration (min)" = "UBD",
             "Power-law exponent alpha" = "alpha", 
             "Gini index" = "gini"
             )
  )
       ) +
  geom_point(
    aes(x = CAT_AGE, y = val, color = CAT_AGE),
    position = position_jitter(seed = 123),
    alpha = 0.3
  ) +
  geom_boxplot(
    data = metric_quantiles,
    aes(
      x = CAT_AGE, 
      fill = CAT_AGE,
      ymin = q25 - 1.5 * (q75 - q25),
      lower = q25, 
      middle = q50, 
      upper = q75, 
      ymax = q75 + 1.5 * (q75 - q25)
      ),
  stat = "identity"
  ) +
  labs(
    title = str_wrap("Patterns of sedentary time accumulation according to age in the United States: A 2003-2006 NHANES analysis", width  = 70), 
    subtitle = str_wrap("As age increases, US non-institutionalized civilians become more sedentary, experience more sedentary bouts of relatively long duration, with the longest sedentary bouts getting a higher weight in total sedentary time.", width  = 90),
    caption = str_wrap("Children = from 6 to 12 yr; Adolescents = from 13 to 17 yr; Adults = from 18 to 64 yr; Older adults = 65 yr and above. The boxplots have been manually built from the sampling weights-based estimates of the quantiles of the metrics. The lower and upper whiskers extend up to the 1.5 times the interquartile range beyond the box hinges respectively. No data was available for preschoolers.", width = 113),
    x = "", 
    y = ""
    ) +
  scale_fill_brewer(palette = palette) +
  scale_color_brewer(palette = palette) +
  facet_wrap(~ metric, scales = "free_y") +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none",
    plot.title = element_text(face = "bold"),
    plot.caption = element_text(hjust = 0)
  )
fig
```

```{r, echo = FALSE}
ggsave("icampam/fig.tiff", fig, width = 7, height = 7)
```

